# Generated by Django 4.0.1 on 2022-01-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtitle', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pricingfirst', models.CharField(db_index=True, max_length=200)),
                ('pricingsecond', models.CharField(db_index=True, max_length=200, null=True)),
                ('pricingthird', models.CharField(db_index=True, max_length=200, null=True)),
                ('pricingfour', models.CharField(db_index=True, max_length=200, null=True)),
                ('pricingfive', models.CharField(db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(db_index=True, max_length=200)),
                ('projectdescription', models.TextField()),
                ('projectmaintext', models.CharField(db_index=True, max_length=200)),
                ('projectsecondtext', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('questiontext', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewsname', models.CharField(db_index=True, max_length=200)),
                ('reviewstext', models.CharField(db_index=True, max_length=400)),
                ('reviewsinstagram', models.CharField(db_index=True, max_length=400)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page.project')),
            ],
        ),
    ]
