# Generated by Django 4.0.1 on 2022-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_pricing_price_alter_pricing_pricingfive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='pricingfive',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricingfour',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricingsecond',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricingthird',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
