# Generated by Django 4.0.1 on 2022-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_pricing_pricingfive_alter_pricing_pricingfour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewsname', models.CharField(db_index=True, max_length=200)),
                ('reviewstext', models.CharField(db_index=True, max_length=400)),
                ('reviewsinstagram', models.CharField(db_index=True, max_length=400)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
