# Generated by Django 4.0.1 on 2022-01-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_reviews_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='avatar',
        ),
    ]
